# Site settings
title: emf-json
email: g.hillairet@gmail.com
description: "Eclipse Modeling Framework meets JSON"
baseurl: ""
github_username: ghillairet

# Build settings
markdown: redcarpet
redcarpet:
  extensions:
  - fenced_code_blocks
  - footnotes
  - with_toc_data
permalink: pretty
highlighter: rouge
sass:
  style: :compressed
  sass_dir: _sass
